spring:
  application :
    name : config-server

  profiles :
    active : native

  cloud :
    config:
      server :
        native :
          search-locations : classpath:/pdb-config/{application}

server :
  port : 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/